Implement support for pgx's CopyFrom
kyleconroy/sqlc pull request #1352
Opened 2021-12-21 16:32 UTC by Jille

I implemented my own feature request https://github.com/kyleconroy/sqlc/issues/1350.

2022-01-03 09:41 UTC, Jille commented
Any thoughts on this?

2022-01-12 03:47 UTC, kyleconroy requested changes
* Please rename `:copyFrom` to `:copyfrom`.
* We need to return an error if you try to use `:copyfrom` using stdlib PostgreSQL or MySQL
* The newly generated code should live in a different file

Let me know if you have any questions.

2022-01-12 03:47 UTC, kyleconroy commented on internal/codegen/golang/templates/pgx/queryCode.tmpl
> +{{end}}
Let's put this code into a different file, something called `{query}_copyfrom.go`

2022-01-13 03:34 UTC, kyleconroy commented
> Did you want a separate file for each query?

Up to you! Probably easier to make it one file for each package.

> What about settings to override the filename for those?

That can come later in a follow-on PR.

> And what about the MyQueryParams and MyQueryRow structs?

We should keep those where they are today.

Hope that help!

2022-01-13 11:01 UTC, Jille commented
Thanks!

All done. Let me know when you want me to rebase+squash.

2022-01-16 00:26 UTC, kyleconroy approved these changes

2022-01-16 00:26 UTC, merged