Fix nullable colums for subqueries in left and full joins
kyleconroy/sqlc pull request #1462
Opened 2022-03-01 20:12 UTC by richardbizik

There is an issue when performing join on subquery. Fields that should be nullable are not because node is processed as ordinary select node. This pull request fixes the issue.

2022-03-02 06:08 UTC, kyleconroy requested changes
Sorry, the current approach taken in this PR isn't going to work. The sample query added to the left join test is helpful to identify the problem.

2022-03-02 06:08 UTC, kyleconroy commented on internal/sql/astutils/walk.go
> +			}
The astutils package does not directly mutate the AST, so this can't go here.

2022-03-02 06:08 UTC, kyleconroy commented on internal/sql/ast/range_subselect.go
>  type RangeSubselect struct {
This type is based on the type here (https://pkg.go.dev/github.com/pganalyze/pg_query_go/v2#RangeSubselect), which does not include join information.

2022-03-03 17:56 UTC, richardbizik commented
I made some changes. Would this approach work better?

2022-03-16 11:12 UTC, sbres commented
I've tried to run the sql query but I seem unable to make it work as is.

Could you check it ?
https://www.db-fiddle.com/f/hXNdApf4mV3Qi1jEgu2egZ/3

2022-03-19 02:06 UTC, kyleconroy requested changes
Is this trying to fix the same problem as https://github.com/kyleconroy/sqlc/pull/1486? If not, I'd like to merge that first before we continue working on this change.

You have some merge conflicts here. Can you rebase?

2022-03-19 10:05 UTC, sbres commented
I've closed #1486 as #1491 applies the same fix.
But they do not fix what this PR is trying to achieve

2022-04-06 18:34 UTC, richardbizik commented
As @sbres pointed out they are fixing a different issue. This PR is trying to solve an issue with nested select statements where an information is lost about the parent being join that should produce nullable results.

2022-04-25 05:12 UTC, closed without merging