add materialized view support
kyleconroy/sqlc pull request #1509
Opened 2022-03-24 16:53 UTC by ludusrusso

This PR Adds materialized view support.

Nota that Materialized View are considered as `CreateTableAs` by `github.com/pganalyze/pg_query_go/v2` so this adds also supporto to "CREATE TABLE AS"

2022-03-24 17:26 UTC, kylecarbs commented
@ludusrusso I _believe_ you intended on tagging @kyleconroy!

2022-03-24 17:30 UTC, ludusrusso commented
😂😂 yep! Sorry!!

2022-03-25 05:38 UTC, kyleconroy requested changes
Since this is implemented via `CREATE TABLE AS`, can we also add a test case for that statement?

2022-03-25 05:38 UTC, kyleconroy commented on internal/sql/catalog/table.go
> +	// }
No need to leave uncommented code around. Can you delete this?

2022-03-25 05:38 UTC, kyleconroy commented on internal/sql/catalog/catalog.go
> +		return c.createTableAs(n, colGen)
Please match the current style in this function and set `err = c.createTableAs`

2022-03-25 05:38 UTC, kyleconroy commented on internal/sql/ast/matview_stmt.go
> +}
I believe this code is unused and can be removed.

2022-03-25 07:45 UTC, ludusrusso commented
> Since this is implemented via `CREATE TABLE AS`, can we also add a test case for that statement?

Fix your suggestions and add a new test case for `create table as`!
Thanks for help!

2022-03-28 23:29 UTC, malonehedges commented
third party bump, looks like comments are addressed cc @kyleconroy 

was trying to use materialized views today so happy to see this on the finish line 😄

2022-03-29 03:40 UTC, kyleconroy approved these changes

2022-03-29 03:40 UTC, merged