Pydantic models config field
kyleconroy/sqlc pull request #1538
Opened 2022-04-10 10:56 UTC by danicc097

Since dataclasses are the default since #939, I added an optional `use_pydantic_models` field to use Pydantic for all models (discussed since #923) which requires much less boilerplate later at least for my use case

2022-04-10 22:07 UTC, kyleconroy requested changes
Thanks for the first draft. Requested a few changes; let me know if you have any questions.

2022-04-10 22:07 UTC, kyleconroy commented on protos/plugin/codegen.proto
> +  bool use_pydantic_models = 6;
To match the other configuration options, rename this to `emit_pydantic_models`.

2022-04-10 22:07 UTC, kyleconroy commented on examples/python/requirements.txt
> +pydantic~=1.9.0
remove

2022-04-10 22:07 UTC, kyleconroy commented on internal/plugin/codegen.pb.go
> +// 	protoc        v3.6.1
Please install the same versions of protoc and protoc-gen-go.

2022-04-10 22:07 UTC, kyleconroy commented on examples/python/sqlc.json
> +          "use_pydantic_models": true
Instead of updating the example, please add a new end-to-end test for Pydantic models.

2022-04-10 22:45 UTC, danicc097 commented on examples/python/requirements.txt
> +pydantic~=1.9.0
isn't this required for ci to pass?

2022-04-20 04:20 UTC, kyleconroy approved these changes

2022-04-20 04:23 UTC, merged