Draft: Support JSON tags for nullable enum structs
kyleconroy/sqlc pull request #2121
Opened 2023-03-01 21:46 UTC by mikemherron

Move tag utility functions in to own source file.

Resolves #2115

2023-03-09 13:28 UTC, mikemherron commented
Sorry for the tag @kyleconroy but do you have an opinion on this one? If you are in agreement with my config proposal, I have time over the weekend to implement this and update the PR. If you'd rather leave this feature out entirely, no problem, feel free to close the issue.

2023-04-07 20:50 UTC, kyleconroy requested changes
@mikemherron Apologies for not getting to this one sooner.

I think your last point is correct. This could be a breaking change for users, as the JSON format of nullable enums will change. Let's go with your second plan of adding a new configuration option to control this behavior.

2023-04-10 09:31 UTC, mikemherron commented
> @mikemherron Apologies for not getting to this one sooner.
> 
> I think your last point is correct. This could be a breaking change for users, as the JSON format of nullable enums will change. Let's go with your second plan of adding a new configuration option to control this behavior.

No problem @kyleconroy, I should have time to do this over the next week.

2023-04-26 13:23 UTC, mikemherron commented on internal/cmd/shim.go
> +		EmitJsonTagsOnNullEnumStructs: s.EmitJSONTagsOnNullEnumStructs,
Unfortunately, `EmitJsonTagsOnNullEnumStructs` is the longest config property name so causes `go fmt` to realign all the config structs, making the PR look a bit busier than it should in places like this.

2023-04-26 13:29 UTC, mikemherron commented
JSON tags on null enum structs are now off by defaullt, and must be turned on with the `emit_json_tags_on_enum_structs` config option. PR is ready to review again.

2023-06-09 15:35 UTC, kyleconroy approved these changes

2023-06-09 15:43 UTC, kyleconroy commented
After thinking about it a bit more, I decided that the extra configuration option isn't worth it. If emit_json_tags is on, we'll add the tags to nullable enums. I cleaned up the code slightly as well.

2023-06-09 15:44 UTC, merged