mysql update docs with env vars, update test with json field, fill cl…
kyleconroy/sqlc pull request #742
Opened 2020-10-23 15:56 UTC by kristijorgji

…eanup function wip see why error happens unkown json type with mysql engine

2020-10-23 16:38 UTC, kyleconroy commented on README.md
> +####For PostgreSQL
Can you add a space between `####` and the title? Same for the other one below

2020-10-23 16:38 UTC, kyleconroy requested changes
The ondeck example is shared across MySQL and PostgreSQL, so I'd like to keep it the same. Please remove the added JSON column. A MySQL [JSON example](https://github.com/kyleconroy/sqlc/blob/master/internal/endtoend/testdata/json/mysql/query.sql) already exists in the form of an end-to-end test.

Really appreciate the README updates!

2020-10-23 18:38 UTC, kristijorgji commented
> The ondeck example is shared across MySQL and PostgreSQL, so I'd like to keep it the same. Please remove the added JSON column. A MySQL [JSON example](https://github.com/kyleconroy/sqlc/blob/master/internal/endtoend/testdata/json/mysql/query.sql) already exists in the form of an end-to-end test.
> 
> Really appreciate the README updates!

Done, reverted that change please re-review

2020-10-26 15:48 UTC, kyleconroy approved these changes
Thanks! I've rebased your changes onto master and will merge once the build passes.

2020-10-26 15:53 UTC, merged