Kotlin mysql
kyleconroy/sqlc pull request #775
Opened 2020-11-09 21:37 UTC by mightyguava

Not much changed really.

[x] Added support for `:execresult`
[x] Add Kotlin MySQL examples and get tests working.
[ ] Add support for all the new mysql types

2020-11-09 21:38 UTC, mightyguava commented on internal/cmd/generate.go
> +				parseOpts.UsePositionalParameters = true
This switch breaks MySQL since it's trying to replace non-existent `$1` to `?`. Not sure if some clever renaming would be useful here

2020-11-10 01:58 UTC, mightyguava commented on .github/workflows/ci.yml
> +        MYSQL_PORT: ${{ job.services.mysql.ports['3306'] }}
This probably never worked? It probably interpolated into the empty string, and the tests used the default port which is 3306

2020-11-10 14:12 UTC, tirsen commented
No example for a mysql `List<String>` query argument?

2020-11-10 14:13 UTC, tirsen approved these changes

2020-11-10 14:18 UTC, mightyguava commented
> No example for a mysql `List<String>` query argument?

Not supported. sqlc doesn't currently have support for variable length arguments AFAIK and MySQL doesn't have support for passing an array as a single parameter. It would be nice to find a solution for this.

2020-11-10 15:08 UTC, mightyguava commented
Looks like passing slices is being discussed in https://github.com/kyleconroy/sqlc/issues/695

2020-11-14 17:09 UTC, kyleconroy requested changes
@mightyguava I merged in your PR that removed the runtime, which has caused merge conflicts. Can you update this PR with the latest master?

2020-11-14 17:38 UTC, mightyguava commented
I did a rebase and git auto-resolved the conflicts.

2020-11-14 17:57 UTC, kyleconroy approved these changes

2020-11-14 17:57 UTC, merged