Override globs
kyleconroy/sqlc pull request #862
Opened 2021-01-26 05:48 UTC by zelch

So, I'm going to start with the use case.

Our MariaDB database has a lot of KSUIDs, enough that I would be better off writing a tool to automate building the override statements than doing it by hand.

It would be nice if we could just override on type, replace 'binary(20)' with 'github.com/segmentio/ksuid.KSUID' and call it a day.

Sadly, at least the mysql parser turns 'binary(20)' into 'char' well before the override code gets it.  In fact, it does this well before any of the sqlc code gets it.

That leaves doing it by column name, but as mentioned above...  There are quite a lot of them.

On the other hand, our naming convention is at least vaguely straight forward.  The columns all end with _ksuid, so we can automatically detect them.

But why write rules to do this, and have a huge override table, when we can just add globbing support to sqlc?

And so I did that instead. :)

This passes all of the tests, and is reasonably straight forward.

2021-01-26 06:04 UTC, kyleconroy commented
Can you attach your sqlc.yaml or sqlc.json file? I'd like to see how this works in practice.

2021-01-26 06:12 UTC, zelch commented
Looks like I should update to version 2, but here you go.

[sqlc.yaml.txt](https://github.com/kyleconroy/sqlc/files/5871499/sqlc.yaml.txt)

2021-02-28 21:46 UTC, zelch commented
Ping on this @kyleconroy

2021-04-12 17:20 UTC, zelch commented
These changes have been rebased on the current head, specifically to add support for the python code generation.

2021-06-28 05:45 UTC, kyleconroy requested changes
I like this change in theory. Before we can get it merged, there will need to be more tests and documentation. If you'd like to write those tests, great. If not, it may be a few more months before this gets merged.

2021-09-12 23:51 UTC, kyleconroy commented
@zelch Going to close this one out, as it has conflicts and no tests. I'd be happy to support this change, but it needs to have test coverage.

2021-09-12 23:51 UTC, closed without merging